<a href="https://colab.research.google.com/github/sc7-cloud/TFG---GOOGLE-COLAB-C-DIGOS-/blob/main/MODELOS_DE_PREDICCI%C3%93N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np






data = pd.read_excel('/content/Artistas.xlsx')



data['log_Seguidores_Spotify'] = np.log(data['Seguidores en Spotify'] + 1)
data['log_Oyentes_mensuales_Spotify'] = np.log(data['Oyentes mensuales en Spotify'] + 1)


data.to_excel('nuevo_archivo_transformado.xlsx', index=False)


print(data[['Seguidores en Spotify', 'log_Seguidores_Spotify', 'Oyentes mensuales en Spotify', 'log_Oyentes_mensuales_Spotify']].head())


   Seguidores en Spotify  log_Seguidores_Spotify  \
0                 704502               13.465248   
1               13020064               16.382002   
2                5355925               15.493714   
3               12859303               16.369578   
4                4321836               15.279191   

   Oyentes mensuales en Spotify  log_Oyentes_mensuales_Spotify  
0                      42896849                      17.574309  
1                      52843480                      17.782845  
2                      31490006                      17.265181  
3                      41343279                      17.537420  
4                      29445103                      17.198038  


In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler



data = pd.read_excel('/content/nuevo_archivo_transformado.xlsx')





X = data[['log_Seguidores_Spotify', 'log_Oyentes_mensuales_Spotify', 'Tasa de conversión en Spotify', 'Me gusta en TikTok', 'Vistas en TikTok']]
y = data['Oyentes mensuales en Spotify']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
y_pred_rf = rf_model.predict(X_test_scaled)


gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train_scaled, y_train)
y_pred_gb = gb_model.predict(X_test_scaled)


lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_scaled, y_train)
y_pred_lr = lr_model.predict(X_test_scaled)


print("Random Forest:")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

print("\nGradient Boosting:")
print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gb))
print("Classification Report:\n", classification_report(y_test, y_pred_gb))

print("\nLogistic Regression:")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))
print("Classification Report:\n", classification_report(y_test, y_pred_lr))


Random Forest:
Accuracy: 0.0
Confusion Matrix:
 [[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

     1046315       0.00      0.00      0.00       1.0
     1072000       0.00      0.00      0.00       0.0
     1137212       0.00      0.00      0.00       1.0
     1190821       0.00      0.00      0.00       1.0
     1236353       0.00      0.00      0.00       1.0
     1302132       0.00      0.00      0.00       1.0
     1470805       0.00      0.00      0.00       1.0
     1479110       0.00      0.00      0.00       0.0
     1534952       0.00      0.00      0.00       1.0
     1539037       0.00      0.00      0.00       0.0
     1549684       0.00      0.00      0.00       0.0
     1809115       0.00      0.00      0.00       0.0
     1859223       0.00      0.00      0.00       1.0
     1939744       0.00      0.00      0.00       0

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler


data = pd.read_excel('nuevo_archivo_transformado.xlsx')


X = data[['log_Seguidores_Spotify', 'log_Oyentes_mensuales_Spotify', 'Tasa de conversión en Spotify', 'Me gusta en TikTok', 'Vistas en TikTok']]
y = data['Oyentes mensuales en Spotify']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
y_pred_rf = rf_model.predict(X_test_scaled)


gb_model = GradientBoostingRegressor(n_estimators=100, random_state=42)
gb_model.fit(X_train_scaled, y_train)
y_pred_gb = gb_model.predict(X_test_scaled)


lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)
y_pred_lr = lr_model.predict(X_test_scaled)


print("Random Forest Regressor:")
print("Mean Squared Error:", mean_squared_error(y_test, y_pred_rf))
print("R2 Score:", r2_score(y_test, y_pred_rf))

print("\nGradient Boosting Regressor:")
print("Mean Squared Error:", mean_squared_error(y_test, y_pred_gb))
print("R2 Score:", r2_score(y_test, y_pred_gb))

print("\nLinear Regression:")
print("Mean Squared Error:", mean_squared_error(y_test, y_pred_lr))
print("R2 Score:", r2_score(y_test, y_pred_lr))


Random Forest Regressor:
Mean Squared Error: 435217062013.8301
R2 Score: 0.9964779381596575

Gradient Boosting Regressor:
Mean Squared Error: 506657489818.03754
R2 Score: 0.9958997953739342

Linear Regression:
Mean Squared Error: 27338504381691.33
R2 Score: 0.7787588965164843


In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler


data = pd.read_excel('nuevo_archivo_transformado.xlsx')


data['log_Oyentes_mensuales_Spotify'] = np.log(data['Oyentes mensuales en Spotify'] + 1)


X = data[['log_Seguidores_Spotify', 'log_Oyentes_mensuales_Spotify', 'Tasa de conversión en Spotify', 'Me gusta en TikTok', 'Vistas en TikTok']]
y = data['log_Oyentes_mensuales_Spotify']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
y_pred_rf = rf_model.predict(X_test_scaled)


gb_model = GradientBoostingRegressor(n_estimators=100, random_state=42)
gb_model.fit(X_train_scaled, y_train)
y_pred_gb = gb_model.predict(X_test_scaled)


lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)
y_pred_lr = lr_model.predict(X_test_scaled)


print("Random Forest Regressor:")
print("Mean Squared Error:", mean_squared_error(y_test, y_pred_rf))
print("R2 Score:", r2_score(y_test, y_pred_rf))

print("\nGradient Boosting Regressor:")
print("Mean Squared Error:", mean_squared_error(y_test, y_pred_gb))
print("R2 Score:", r2_score(y_test, y_pred_gb))

print("\nLinear Regression:")
print("Mean Squared Error:", mean_squared_error(y_test, y_pred_lr))
print("R2 Score:", r2_score(y_test, y_pred_lr))


Random Forest Regressor:
Mean Squared Error: 0.0007013177129076775
R2 Score: 0.9992867846609401

Gradient Boosting Regressor:
Mean Squared Error: 0.0007134572873459533
R2 Score: 0.9992744391425827

Linear Regression:
Mean Squared Error: 0.0
R2 Score: 1.0


In [ ]:

rf_model = RandomForestRegressor(n_estimators=100, max_depth=10, min_samples_split=10, random_state=42)
rf_model.fit(X_train_scaled, y_train)
y_pred_rf = rf_model.predict(X_test_scaled)


gb_model = GradientBoostingRegressor(n_estimators=100, max_depth=10, random_state=42)
gb_model.fit(X_train_scaled, y_train)
y_pred_gb = gb_model.predict(X_test_scaled)


In [ ]:
from sklearn.model_selection import cross_val_score


rf_cv_scores = cross_val_score(rf_model, X_train_scaled, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation MSE for Random Forest:", -rf_cv_scores.mean())


gb_cv_scores = cross_val_score(gb_model, X_train_scaled, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation MSE for Gradient Boosting:", -gb_cv_scores.mean())


lr_cv_scores = cross_val_score(lr_model, X_train_scaled, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation MSE for Linear Regression:", -lr_cv_scores.mean())


Cross-Validation MSE for Random Forest: 0.0024993881710238955
Cross-Validation MSE for Gradient Boosting: 0.001014481814555597
Cross-Validation MSE for Linear Regression: 1.9524307404220043e-30


In [ ]:

noise_train = np.random.normal(0, 0.1, size=X_train_scaled.shape)
noise_test = np.random.normal(0, 0.1, size=X_test_scaled.shape)


print(f"Forma de X_train_scaled: {X_train_scaled.shape}")
print(f"Forma de ruido_train: {noise_train.shape}")
print(f"Forma de X_test_scaled: {X_test_scaled.shape}")
print(f"Forma de ruido_test: {noise_test.shape}")


X_train_noisy = X_train_scaled + noise_train
X_test_noisy = X_test_scaled + noise_test


rf_model.fit(X_train_noisy, y_train)
y_pred_rf_noisy = rf_model.predict(X_test_noisy)


print("MSE con ruido (Random Forest):", mean_squared_error(y_test, y_pred_rf_noisy))




Forma de X_train_scaled: (321, 5)
Forma de ruido_train: (321, 5)
Forma de X_test_scaled: (81, 5)
Forma de ruido_test: (81, 5)
MSE con ruido (Random Forest): 0.011029465142508106


In [ ]:
from sklearn.linear_model import Ridge


ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train_scaled, y_train)
y_pred_ridge = ridge_model.predict(X_test_scaled)


print("Mean Squared Error (Ridge):", mean_squared_error(y_test, y_pred_ridge))
print("R2 Score (Ridge):", r2_score(y_test, y_pred_ridge))


Mean Squared Error (Ridge): 6.302397374746012e-05
R2 Score (Ridge): 0.9999359068451033


In [ ]:

rf_model = RandomForestRegressor(n_estimators=50, max_depth=6, min_samples_split=10, random_state=42)
rf_model.fit(X_train_noisy, y_train)
y_pred_rf = rf_model.predict(X_test_noisy)
print("MSE con Random Forest:", mean_squared_error(y_test, y_pred_rf))
print("R2 con Random Forest:", r2_score(y_test, y_pred_rf))


MSE con Random Forest: 0.010267312139663127
R2 con Random Forest: 0.9895585062602187


In [ ]:

gb_model = GradientBoostingRegressor(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)
gb_model.fit(X_train_noisy, y_train)
y_pred_gb = gb_model.predict(X_test_noisy)
print("MSE con Gradient Boosting:", mean_squared_error(y_test, y_pred_gb))
print("R2 con Gradient Boosting:", r2_score(y_test, y_pred_gb))


MSE con Gradient Boosting: 0.014348278856871762
R2 con Gradient Boosting: 0.9854083072743147


In [ ]:

from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train_noisy, y_train)
y_pred_ridge = ridge_model.predict(X_test_noisy)


print("MSE con Ridge:", mean_squared_error(y_test, y_pred_ridge))
print("R2 con Ridge:", r2_score(y_test, y_pred_ridge))


MSE con Ridge: 0.007060000020380404
R2 con Ridge: 0.9928202293830256


In [ ]:
from sklearn.model_selection import cross_val_score


rf_cv_scores = cross_val_score(rf_model, X_train_noisy, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation MSE for Random Forest:", -rf_cv_scores.mean())


gb_cv_scores = cross_val_score(gb_model, X_train_noisy, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation MSE for Gradient Boosting:", -gb_cv_scores.mean())


ridge_cv_scores = cross_val_score(ridge_model, X_train_noisy, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation MSE for Ridge Regression:", -ridge_cv_scores.mean())


Cross-Validation MSE for Random Forest: 0.010297295897152548
Cross-Validation MSE for Gradient Boosting: 0.009904848223311979
Cross-Validation MSE for Ridge Regression: 0.006628291691205819


In [ ]:

noise_train = np.random.normal(0, 0.5, size=X_train_scaled.shape)
noise_test = np.random.normal(0, 0.5, size=X_test_scaled.shape)


X_train_noisy = X_train_scaled + noise_train
X_test_noisy = X_test_scaled + noise_test


In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


X_train_sub, X_valid_sub, y_train_sub, y_valid_sub = train_test_split(X_train_noisy, y_train, test_size=0.2, random_state=42)


gb_model = GradientBoostingRegressor(n_estimators=1000, max_depth=6, learning_rate=0.1, random_state=42)


gb_model.fit(X_train_sub, y_train_sub)


y_pred_gb = gb_model.predict(X_valid_sub)


print("MSE con Gradient Boosting (sin Early Stopping):", mean_squared_error(y_valid_sub, y_pred_gb))
print("R2 con Gradient Boosting (sin Early Stopping):", r2_score(y_valid_sub, y_pred_gb))


MSE con Gradient Boosting (sin Early Stopping): 0.1278595202073551
R2 con Gradient Boosting (sin Early Stopping): 0.8010471383735622


In [ ]:
from sklearn.metrics import r2_score


y_pred_train = gb_model.predict(X_train_noisy)


r2_train = r2_score(y_train, y_pred_train)
print(f"R² en entrenamiento: {r2_train}")


y_pred_test = gb_model.predict(X_test_noisy)


r2_test = r2_score(y_test, y_pred_test)
print(f"R² en prueba: {r2_test}")


R² en entrenamiento: 0.9627248659648793
R² en prueba: 0.8501829672886044


In [ ]:
gb_model = GradientBoostingRegressor(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.05,
    random_state=42
)
gb_model.fit(X_train_noisy, y_train)
y_pred_gb = gb_model.predict(X_test_noisy)

print(f"R² en entrenamiento: {r2_score(y_train, gb_model.predict(X_train_noisy))}")
print(f"R² en prueba: {r2_score(y_test, y_pred_gb)}")


R² en entrenamiento: 0.9891774754011492
R² en prueba: 0.8581955519955642


In [ ]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=5,
    min_samples_split=10,
    random_state=42
)
rf_model.fit(X_train_noisy, y_train)
y_pred_rf = rf_model.predict(X_test_noisy)

print(f"R² en entrenamiento: {r2_score(y_train, rf_model.predict(X_train_noisy))}")
print(f"R² en prueba: {r2_score(y_test, y_pred_rf)}")


R² en entrenamiento: 0.9251256493167446
R² en prueba: 0.8471174663416859


In [ ]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train_noisy, y_train)
y_pred_ridge = ridge_model.predict(X_test_noisy)

print(f"R² en entrenamiento: {r2_score(y_train, ridge_model.predict(X_train_noisy))}")
print(f"R² en prueba: {r2_score(y_test, y_pred_ridge)}")


R² en entrenamiento: 0.8849696979645438
R² en prueba: 0.8718785318785442


In [ ]:
gb_model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.01,
    max_depth=5,
    random_state=42
)
gb_model.fit(X_train_noisy, y_train)
y_pred_gb = gb_model.predict(X_test_noisy)

print(f"R² en entrenamiento: {r2_score(y_train, gb_model.predict(X_train_noisy))}")
print(f"R² en prueba: {r2_score(y_test, y_pred_gb)}")


R² en entrenamiento: 0.9447559473662018
R² en prueba: 0.8197712370436584


In [ ]:
from sklearn.model_selection import cross_val_score


rf_cv_scores = cross_val_score(rf_model, X_train_noisy, y_train, cv=5, scoring='neg_mean_squared_error')
print(f"Cross-Validation MSE for Random Forest: {-rf_cv_scores.mean()}")


gb_cv_scores = cross_val_score(gb_model, X_train_noisy, y_train, cv=5, scoring='neg_mean_squared_error')
print(f"Cross-Validation MSE for Gradient Boosting: {-gb_cv_scores.mean()}")


Cross-Validation MSE for Random Forest: 0.11147644415345961
Cross-Validation MSE for Gradient Boosting: 0.1263775978237321


In [ ]:
from sklearn.linear_model import Ridge


ridge_model = Ridge(alpha=1.0)


ridge_model.fit(X_train, y_train)


y_pred = ridge_model.predict(X_test)


from sklearn.metrics import mean_squared_error, r2_score
print(f"R² en entrenamiento: {r2_score(y_train, ridge_model.predict(X_train))}")
print(f"R² en prueba: {r2_score(y_test, y_pred)}")


R² en entrenamiento: 0.9998873167838311
R² en prueba: 0.9998805855233401


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=6.38661e-22): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
